# Site settings
title: HOME - Bitcoin Mantra Series!
email: 
description: 
baseurl: ""
url: https://bitcoin-mantra.github.io
logo: /assets/img/BitcoinMantra.png
twitter_username: vthakurtwi
github_username:  bitcoin-mantra 

github:
  username: bitcoin-mantra # change to your github username
  twitter_username: vthakurtwi
  github_username:  bitcoin-mantra  

# Build settings
markdown: bitcoin-mantra
permalink: pretty

highlighter: rouge
bitcoin-mantra:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge